global:
    checkNewVersion: true
    sendAnonymousUsage: false

certificatesResolvers:
    prodssl:
        acme:
            email: "user@example.com"
            storage: "/acme/prod.json"
            tlsChallenge: {}

providers:
    docker:
        swarmMode: true
        watch: true
        network: "traefik"
        exposedByDefault: false
    file:
        watch: true
        filename: "/etc/traefik/traefik.yml"

entryPoints:
    web:
        address: :80
        http:
            redirections:
                entryPoint:
                    to: websecure
                    scheme: https
    websecure:
        address: :443
        http:
            middlewares:
                - secHeaders@file
                - cache@file
                - compress@file

http:
    middlewares:
        secHeaders:
            headers:
                sslRedirect: true
                stsIncludeSubdomains: true
                stspreload: true
                stsseconds: 31536000
        cache:
            plugin:
                plugin-simplecache:
                    path: /tmp
        compress:
            compress: {}

pilot:
    token: "XXX"

experimental:
    plugins:
        plugin-simplecache:
            moduleName: "github.com/traefik/plugin-simplecache"
            version: "v0.2.1"
